#!/bin/bash

# Install dependencies
apt update
apt install -y ddclient btrfs-tools unattended-upgrades

# Prepare USB (data) storage
mkdir -p /mnt/usb/
grep /mnt/usbd/ /etc/fstab || printf "$(blkid /dev/sda1 -o export | grep ^UUID=) /mnt/usb/ btrfs noatime 0 0\n" | sudo tee -a /etc/fstab
mount /mnt/usb
ls -ld /mnt/usb/filetclouddata || btrfs subvolume create /mnt/usb/filetclouddata
chmod a+w /mnt/usb/filetclouddata
mkdir -p /mnt/usb/.snapshots

# Configure auto-update
sed -i 's:Debian:Raspbian:g' /etc/apt/apt.conf.d/50unattended-upgrades

# Install filet-cloud-tools
make -C filet-cloud/filetcloudtools
dpkg -i filet-cloud/filetcloudtools/filetcloudtools.deb
systemctl enable filet-cloud-actions
systemctl restart filet-cloud-actions

# Install filet-cloud-web
# Need newer golang
if [ ! -e filet-cloud/go ]; then
	cd filet-cloud
	wget https://golang.org/dl/$(curl https://golang.org/dl/ | grep armv6l | grep -v beta | head -n 1 | awk -F'[<>]' {'print $5'}) -O golang.tar.gz
	tar zxf golang.tar.gz
	cd -
fi
# Now get and build filet-cloud-web
ls -1d filet-cloud/filet-cloud-web || git clone https://github.com/fuglaro/filet-cloud-web.git filet-cloud/filet-cloud-web
git -C filet-cloud/filet-cloud-web/ pull
cd filet-cloud/filet-cloud-web; ../go/bin/go build; cd -
# Register and enable the service
cp filet-cloud/filet-cloud-web.service /etc/systemd/system/
systemctl enable filet-cloud-web
systemctl restart filet-cloud-web

# Configure daily snapshots (4am)
crontab -u pi -l | grep filet-cloud-snapshot || (crontab -u pi -l; echo '5 4 * * * filet-cloud-snapshot') | crontab -u pi -

# Update the display
crontab -u pi -l | grep filet-cloud-status || (crontab -u pi -l; echo '*/5 * * * * filet-cloud-status') | crontab -u pi -
filet-cloud-status
