#!/bin/bash

[ -e /etc/nginx/conf.d/filet-cloud.conf ] && exit

# Generate the initial nginx config
read -p 'Please enter the domain: ' domain
[ -z "${domain}" ] && exit
cp filet-cloud/filet-cloud.conf /etc/nginx/conf.d/filet-cloud.conf
sed -i -e "s:{{DOMAIN}}:${domain}:g" /etc/nginx/conf.d/filet-cloud.conf

# Start nginx
nginx -s reload

# Setup lets encrypt
certbot --nginx -d ${domain}

# Daily crontab for cert renewal
crontab -l | grep 'certbot renew' || (crontab -l; echo '12 13 * * * /usr/bin/certbot renew --quiet') | crontab -

# Register and enable the service to renew certificates on startup
cp filet-cloud/cert-renewal.service /etc/systemd/system/
systemctl enable cert-renewal
systemctl restart cert-renewal

