#!/bin/bash

set -e

read -p 'Please enter the domain: ' DOMAIN </dev/tty
[ -z "$DOMAIN" ] && { echo "error: DOMAIN required."; exit 1; }

# Disable the LED (now and on boot)
echo none | sudo tee /sys/class/leds/board-led/trigger
cat <<EOF | sudo tee /etc/sysfs.d/led.conf
class/leds/board-led/trigger = none
EOF

# Install dependencies.
sudo apt install -y ddclient btrfs-progs

# Setup the USB Drive
# Find the largest sda mount.
UUID=$(lsblk -n -b -o NAME,UUID -x SIZE | grep "^sd" | sed -e 's:[^ ]* *::' | grep -v '^$' | tail -n 1)
FSTYPE=$(lsblk -n -b -o UUID,FSTYPE | grep "^$UUID " | sed -e 's:[^ ]* *::' | grep -v '^$' | tail -n 1)
grep "^UUID=$UUID" /etc/fstab || \
  printf "UUID=$UUID /mnt/filetcloud $FSTYPE defaults,noatime 0 0" | sudo tee -a /etc/fstab
sudo mkdir -p /mnt/filetcloud
mountpoint /mnt/filetcloud || sudo mount /mnt/filetcloud

sudo systemctl stop filet-cloud || true

# Install filet-cloud.
sudo wget https://github.com/fuglaro/filet-cloud/releases/latest/download/filet-cloud-raspberry-pi -O /usr/bin/filet-cloud
sudo chmod a+x /usr/bin/filet-cloud

# Setup filet-cloud as a service.
cat <<EOF | sudo tee /etc/systemd/system/filet-cloud.service
[Unit]
Description=Filet Cloud

[Service]
User=root
Environment="FC_DOMAIN=$DOMAIN"
Environment="FC_DIR=/mnt/filetcloud/data/USERNAME"
ExecStart=/usr/bin/filet-cloud
Restart=always

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl enable filet-cloud
sudo systemctl restart filet-cloud

# Allow COLORTERM env var to be passed in by filet-cloud.
if grep COLORTERM /etc/ssh/sshd_config; then :
else
printf "\n\nAcceptEnv COLORTERM\n\n" | sudo tee -a /etc/ssh/sshd_config
fi

# Setup the btrfs daily snapshots
cat <<EOF | sudo tee /etc/cron.daily/filet-cloud-snapshots
#!/bin/sh
btrfs subvolume snapshot -r /mnt/filetcloud/data /mnt/filetcloud/.snapshots/filetclouddata-\$(date +%y%m%d-%H%M%S)
EOF
sudo chmod a+x /etc/cron.daily/filet-cloud-snapshots
