#!/bin/bash

read -p 'Please enter the domain: ' domain
[ -z "${domain}" ] && exit

# Install dependencies
apt update
apt install -y ddclient btrfs-tools unattended-upgrades certbot python-certbot-nginx imagemagick libpam-google-authenticator

# Prepare USB (data) storage
mkdir -p /mnt/usb/
grep /mnt/usbd/ /etc/fstab || printf "$(blkid /dev/sda1 -o export | grep ^UUID=) /mnt/usb/ btrfs noatime 0 0\n" | sudo tee -a /etc/fstab
mount /mnt/usb
ls -ld /mnt/usb/filetclouddata || btrfs subvolume create /mnt/usb/filetclouddata
chmod a+w /mnt/usb/filetclouddata
mkdir -p /mnt/usb/.snapshots

# Configure auto-update
sed -i 's:Debian:Raspbian:g' /etc/apt/apt.conf.d/50unattended-upgrades

# Install filet-cloud-tools
make -C filetcloudtools
dpkg -i filetcloudtools/filetcloudtools.deb
systemctl enable filet-cloud-actions
systemctl restart filet-cloud-actions
cat <<EOF | sudo tee /etc/sudoers.d/000_filetcloud
ALL ALL=(root) NOPASSWD: /usr/bin/btrfs subvolume list *
ALL ALL=(root) NOPASSWD: /usr/bin/vcgencmd measure_temp
EOF
# Install filet-cloud
wget https://github.com/fuglaro/filet-cloud/releases/download/1.0.0/filet-cloud-raspberry-pi -O /usr/bin/filet-cloud
chmod a+x /usr/bin/filet-cloud
# Register and enable the service
cp filet-cloud-web.service /etc/systemd/system/
sed -i -e "s:{{DOMAIN}}:${domain}:g" /etc/systemd/system/filet-cloud-web.service
systemctl enable filet-cloud-web
systemctl restart filet-cloud-web

# Configure daily snapshots (4am)
crontab -u pi -l | grep filet-cloud-snapshot || (crontab -u pi -l; echo '5 4 * * * filet-cloud-snapshot') | crontab -u pi -

# Update the display
crontab -u pi -l | grep filet-cloud-status || (crontab -u pi -l; echo '*/5 * * * * filet-cloud-status') | crontab -u pi -
filet-cloud-status

# Generate the initial nginx config
cp nginx.conf /etc/nginx/conf.d/filet-cloud.conf
sed -i -e "s:{{DOMAIN}}:${domain}:g" /etc/nginx/conf.d/filet-cloud.conf

# Start nginx
nginx -s reload

# Setup lets encrypt
certbot --nginx -d ${domain}

# Daily crontab for cert renewal
crontab -l | grep 'certbot renew' || (crontab -l; echo '12 13 * * * /usr/bin/certbot renew --quiet') | crontab -

# Register and enable the service to renew certificates on startup
cp cert-renewal.service /etc/systemd/system/
systemctl enable cert-renewal
systemctl restart cert-renewal

# Allow COLORTERM env var to be passed in by filet-cloud
echo | sudo tee -a /etc/ssh/sshd_config
echo "AcceptEnv COLORTERM" | sudo tee -a /etc/ssh/sshd_config

# Setup 2FA
echo "Setting up Two Factor Authentication"
echo "" | sudo tee -a /etc/pam.d/sshd
echo "auth required pam_google_authenticator.so nullok" | sudo tee -a /etc/pam.d/sshd
echo "auth required pam_permit.so" | sudo tee -a /etc/pam.d/sshd
sudo sed -i 's/^ChallengeResponseAuthentication no$/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
echo | sudo tee -a /etc/ssh/sshd_config
echo "AuthenticationMethods publickey password keyboard-interactive" | sudo tee -a /etc/ssh/sshd_config
